version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@esjvb4vbihzukbzl_tp?TNS_ADMIN=/app/oracle_wallet
      - spring.datasource.username=JAVA_ARQ
      - spring.datasource.password=ClaseArquitectura123#
    restart: always